#SETUP
NAME		=	fdf
CC			=	gcc
FLAGS		=	-Wall -Wextra -Werror
RM			=	rm -rf
FRAMEWORK	=	-Lmlx -lm -lmlx -framework OpenGL -framework AppKit

#FILES AND PATH
HEADERS		=	includes/fdf.h gnl/get_next_line.h

SRC_SRCS	=	ONLY_TEST.c fdf.c grids.c pars.c memory.c error.c
SRC_DIR		=	sources/
SRC			=	$(addprefix $(SRC_DIR), $(SRC_SRCS))
OBJ			=	$(SRC:.c=.o)

FUNC_SRCS	=	ft_atoi.c ft_isdigit.c
FUNC_DIR	=	functions/
FUNC 		=	$(addprefix $(FUNC_DIR), $(FUNC_SRCS))\
				gnl/get_next_line.c gnl/get_next_line_utils.c
OBJ_F		=	$(FUNC:.c=.o)

#COMMANDS
%.o: %.c $(HEADERS) Makefile
				@${CC} ${FLAGS} -Imlx -c $< -o $@

# CHANGE IN $(NAME) -> @$(CC) $(OBJ) $(OBJ_F) $(FRAMEWORK) -o $(NAME)

$(NAME):		$(OBJ) $(OBJ_F)
				@$(CC) $(OBJ) $(OBJ_F) $(FRAMEWORK) -o $(NAME)
				@echo -e "$(GREEN)$(NAME) created!$(DEFAULT)"

all:			@make -C mlx/ all
				$(NAME)

clean:
				@$(RM) $(OBJ)
				@$(RM) $(OBJ_F)
				@make -C mlx/ clean
				@echo -e "$(YELLOW)object files deleted!$(DEFAULT)"

fclean:			clean
				@$(RM) $(NAME)
				@echo -e "$(RED)all deleted!$(DEFAULT)"

re:				fclean all

.PHONY:		all clean fclean re

#COLORS
RED = \033[1;31m
GREEN = \033[1;32m
YELLOW = \033[1;33m
DEFAULT = \033[0m
